/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package phaseportrait;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import rungekutta.Point;
import rungekutta.RungeKutta;

/**
 *
 * @author victor
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEquation = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblFt = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtFx = new javax.swing.JTextField();
        lblt0 = new javax.swing.JLabel();
        lbly0 = new javax.swing.JLabel();
        lblz0 = new javax.swing.JLabel();
        txty0 = new javax.swing.JTextField();
        txtz0 = new javax.swing.JTextField();
        txtt0 = new javax.swing.JTextField();
        lblProb = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        txtH = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        txtMax = new javax.swing.JTextField();
        pnlYT = new phaseportrait.pnlGraph();
        lblCoorYT = new javax.swing.JLabel();
        sldThYT = new javax.swing.JSlider();
        btnSolve = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        pnlYZ = new phaseportrait.pnlGraph();
        lblCoorZY = new javax.swing.JLabel();
        sldThZY = new javax.swing.JSlider();
        lblYT = new javax.swing.JLabel();
        lblZY = new javax.swing.JLabel();
        btnDropPlane = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ОДУ второго порядка");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(100, 100, 100, 100));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));

        lblEquation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEquation.setText("y'' + ay' + by = f(t)");
        lblEquation.setName(""); // NOI18N

        lblA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblA.setText("a =");

        lblB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblB.setText("b =");

        lblFt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFt.setText("f(t) =");

        txtA.setText("0");

        txtB.setText("0");

        txtFx.setText("0");

        lblt0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblt0.setText("t0 =");

        lbly0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbly0.setText("y(t0) =");

        lblz0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblz0.setText("y'(t0) =");

        txty0.setText("0");

        txtz0.setText("0");

        txtt0.setText("0");

        lblProb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblProb.setText("Задача Коши");

        lblH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblH.setText("шаг =");

        lblMin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMin.setText("t min =");

        lblMax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMax.setText("t max =");

        txtH.setText("0.01");

        txtMin.setText("0");

        txtMax.setText("20");

        pnlYT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true));
        pnlYT.setForeground(new java.awt.Color(255, 0, 0));
        pnlYT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pnlYT.setOpaque(false);
        pnlYT.setPreferredSize(new java.awt.Dimension(340, 340));
        pnlYT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlYTMouseMoved(evt);
            }
        });

        lblCoorYT.setText("0; 0");

        sldThYT.setValue(20);
        sldThYT.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldThYTStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlYTLayout = new javax.swing.GroupLayout(pnlYT);
        pnlYT.setLayout(pnlYTLayout);
        pnlYTLayout.setHorizontalGroup(
            pnlYTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlYTLayout.createSequentialGroup()
                .addComponent(sldThYT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(lblCoorYT)
                .addContainerGap())
        );
        pnlYTLayout.setVerticalGroup(
            pnlYTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlYTLayout.createSequentialGroup()
                .addGroup(pnlYTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoorYT)
                    .addComponent(sldThYT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSolve.setText("Построить");
        btnSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolveActionPerformed(evt);
            }
        });

        btnClear.setText("Очистить");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        pnlYZ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true));
        pnlYZ.setForeground(new java.awt.Color(0, 0, 255));
        pnlYZ.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pnlYZ.setOpaque(false);
        pnlYZ.setPreferredSize(new java.awt.Dimension(340, 340));
        pnlYZ.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlYZMouseMoved(evt);
            }
        });

        lblCoorZY.setText("0; 0");

        sldThZY.setValue(20);
        sldThZY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldThZYStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlYZLayout = new javax.swing.GroupLayout(pnlYZ);
        pnlYZ.setLayout(pnlYZLayout);
        pnlYZLayout.setHorizontalGroup(
            pnlYZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlYZLayout.createSequentialGroup()
                .addComponent(sldThZY, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(lblCoorZY)
                .addContainerGap())
        );
        pnlYZLayout.setVerticalGroup(
            pnlYZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlYZLayout.createSequentialGroup()
                .addGroup(pnlYZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCoorZY)
                    .addComponent(sldThZY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 323, Short.MAX_VALUE))
        );

        lblYT.setText("График y(t)");

        lblZY.setText("График y'(y)");

        btnDropPlane.setText("Сброс масштаба");
        btnDropPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropPlaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtA, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtB)
                                    .addComponent(txtFx)))
                            .addComponent(lblEquation))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProb)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbly0)
                                    .addComponent(lblz0)
                                    .addComponent(lblt0))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtz0, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtt0)
                                    .addComponent(txty0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMax)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMax))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblH)
                                            .addComponent(lblMin))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtH)
                                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDropPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlYT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlYZ, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblYT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblZY)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquation)
                    .addComponent(lblProb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbly0)
                    .addComponent(txty0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblH)
                    .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSolve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblB)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblz0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtz0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMin)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFx)
                        .addComponent(lblFt)
                        .addComponent(lblt0))
                    .addComponent(txtt0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMax)
                        .addComponent(btnDropPlane)
                        .addComponent(lblMax)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYT)
                    .addComponent(lblZY))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlYZ, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(pnlYT, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setEquation(Double a, Double b, String ft, boolean canChange)
    {
        txtA.setText(a.toString());
        txtB.setText(b.toString());
        txtFx.setText(ft);
        
        txtA.setEnabled(canChange);
        txtB.setEnabled(canChange);
        txtFx.setEnabled(canChange);
    }
    
    private void btnSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolveActionPerformed
        double tmin, tmax, h;
        double a, b, t0, y0, z0;
        String ft;
        tmax = Double.parseDouble(txtMax.getText());
        tmin = Double.parseDouble(txtMin.getText());
        h = Double.parseDouble(txtH.getText());
        a = Double.parseDouble(txtA.getText());
        b = Double.parseDouble(txtB.getText());
        t0 = Double.parseDouble(txtt0.getText());
        y0 = Double.parseDouble(txty0.getText());
        z0 = Double.parseDouble(txtz0.getText());
        ft = txtFx.getText();
        try
        {
            RungeKutta rk = new RungeKutta(a, b, ft, t0, y0, z0, h);
            ArrayList<Point> pts = new ArrayList<>();
            for(double t = t0; t <= tmax; t += h)
            {
                pts.add(rk.getNextPoint());
            }
            rk.setPoint(t0, y0, z0);
            for(double t = t0; t >= tmin; t -= h)
            {
                pts.add(rk.getPreviousPoint());
            }

            Collections.sort(pts);
            Point[] pt = new Point[pts.size()];
            pts.toArray(pt);
            pnlYT.addGraph(pt, pnlGraph.GraphType.YT);
            pnlYZ.addGraph(pt, pnlGraph.GraphType.ZY);
            this.repaint();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.toString() +
                    "\nПопробуйте ввести другую функцию или"
                    + " искать решение в другом диапазоне.", 
                    "Ошибка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSolveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        pnlYT.clear();
        pnlYZ.clear();
        this.repaint();
    }//GEN-LAST:event_btnClearActionPerformed

    private void pnlYTMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlYTMouseMoved
        lblCoorYT.setText(pnlYT.getXCoor() + "; " + pnlYT.getYCoor());
    }//GEN-LAST:event_pnlYTMouseMoved

    private void pnlYZMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlYZMouseMoved
        lblCoorZY.setText(pnlYZ.getXCoor() + "; " + pnlYZ.getYCoor());
    }//GEN-LAST:event_pnlYZMouseMoved

    private void sldThYTStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldThYTStateChanged
        pnlYT.setThickness((float)sldThYT.getValue() / 100);
    }//GEN-LAST:event_sldThYTStateChanged

    private void sldThZYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldThZYStateChanged
        pnlYZ.setThickness((float)sldThZY.getValue() / 100);
    }//GEN-LAST:event_sldThZYStateChanged

    private void btnDropPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropPlaneActionPerformed
        pnlYZ.setPlane(500, 500);
        pnlYT.setPlane(500, 500);
        this.repaint();
    }//GEN-LAST:event_btnDropPlaneActionPerformed

    public static class Runner implements Runnable{
        private double a, b;
        private String ft;
        private boolean canChange;
        
        public Runner(double _a, double _b, String f, boolean cc)
        {
            a = _a;
            b = _b;
            ft = f;
            canChange =  cc;
        }
        
        @Override
        public void run() {
            frmMain f = new frmMain();
            f.setVisible(true);
            f.setEquation(a, b, ft, canChange);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        double a = 0, b = 0;
        String ft = "0";
        System.out.println(args.length);
        if(args.length == 3)
        {
            a = Double.parseDouble(args[0]);
            b = Double.parseDouble(args[1]);
            ft = args[2];
        }
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runner(a, b, ft, true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDropPlane;
    private javax.swing.JButton btnSolve;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblCoorYT;
    private javax.swing.JLabel lblCoorZY;
    private javax.swing.JLabel lblEquation;
    private javax.swing.JLabel lblFt;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblProb;
    private javax.swing.JLabel lblYT;
    private javax.swing.JLabel lblZY;
    private javax.swing.JLabel lblt0;
    private javax.swing.JLabel lbly0;
    private javax.swing.JLabel lblz0;
    private phaseportrait.pnlGraph pnlYT;
    private phaseportrait.pnlGraph pnlYZ;
    private javax.swing.JSlider sldThYT;
    private javax.swing.JSlider sldThZY;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtFx;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtt0;
    private javax.swing.JTextField txty0;
    private javax.swing.JTextField txtz0;
    // End of variables declaration//GEN-END:variables
}
